"""
Routing Models

Defines Pydantic models for structured agent outputs.
"""

from typing import List, Optional, Literal
from pydantic import BaseModel, Field


class SupervisorPlan(BaseModel):
    """Routing plan generated by the Supervisor Agent."""
    
    action: Literal["research", "rewrite"] = Field(
        ..., 
        description="The next high-level action to take. 'research' to gather more info, 'rewrite' to update the draft."
    )
    subtopics: Optional[List[str]] = Field(
        default_factory=list,
        description="A list of 3-5 focused subtopics for parallel research. Required if action is 'research'."
    )
    rewrite_instructions: Optional[str] = Field(
        None,
        description="Clear instructions for the Writer agent to improve the draft. Required if action is 'rewrite'."
    )
